// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.foo.client.managed.ui;

import com.foo.client.managed.request.ApplicationEntityTypesProcessor;
import com.foo.client.managed.request.TimerProxy;
import com.foo.client.scaffold.place.ProxyListPlace;
import com.google.gwt.text.shared.AbstractRenderer;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handleTimer(TimerProxy isNull) {
                setResult("Timers");
            }
        }.process(object.getProxyClass());
    }
}
