// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.foo.client.managed.ui;

import com.foo.client.managed.request.TimerProxy;
import com.foo.client.scaffold.ScaffoldMobileApp;
import com.foo.client.scaffold.ui.MobileProxyListView;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.safehtml.shared.SafeHtml;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.safehtml.shared.SafeHtmlUtils;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.AbstractSafeHtmlRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.text.shared.SafeHtmlRenderer;
import java.util.HashSet;
import java.util.Set;

public abstract class TimerMobileListView_Roo_Gwt extends MobileProxyListView<TimerProxy> {

    protected Set<String> paths = new HashSet<String>();

    public TimerMobileListView_Roo_Gwt(String buttonText, SafeHtmlRenderer<com.foo.client.managed.request.TimerProxy> renderer) {
        super(buttonText, renderer);
    }

    public void init() {
        paths.add("userName");
        paths.add("id");
        paths.add("startDate");
    }
}
