// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.foo;

import com.foo.Timer;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TimerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TimerDataOnDemand: @Component;
    
    private Random TimerDataOnDemand.rnd = new SecureRandom();
    
    private List<Timer> TimerDataOnDemand.data;
    
    public Timer TimerDataOnDemand.getNewTransientTimer(int index) {
        Timer obj = new Timer();
        setStartDate(obj, index);
        setUserName(obj, index);
        return obj;
    }
    
    public void TimerDataOnDemand.setStartDate(Timer obj, int index) {
        Date startDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStartDate(startDate);
    }
    
    public void TimerDataOnDemand.setUserName(Timer obj, int index) {
        String userName = "userName_" + index;
        obj.setUserName(userName);
    }
    
    public Timer TimerDataOnDemand.getSpecificTimer(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Timer obj = data.get(index);
        return Timer.findTimer(obj.getId());
    }
    
    public Timer TimerDataOnDemand.getRandomTimer() {
        init();
        Timer obj = data.get(rnd.nextInt(data.size()));
        return Timer.findTimer(obj.getId());
    }
    
    public boolean TimerDataOnDemand.modifyTimer(Timer obj) {
        return false;
    }
    
    public void TimerDataOnDemand.init() {
        data = Timer.findTimerEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Timer' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.foo.Timer>();
        for (int i = 0; i < 10; i++) {
            Timer obj = getNewTransientTimer(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
